### ISSUE TITLE
LICENSE CC0 not valid

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/uio-carpentry.github.io#11]
Hei!

We need to have a discussion about which licenses we can / should / must give to our uio-carpentry repositories.
According to Norwegian law, we cannot assign a CC0 / PublicDomain license to our repositories. It must be at least a CC-BY for non-software.
You can read about the Norwegian "opphavsrett" here: https://lovdata.no/lov/2018-06-15-40/§5
But please, let's have a discussion!

**Comment by arockenberger** [comment]
What do you think?

**Comment by Sabryr** [comment]
Will get back ASAP

**Comment by naoe-tatara** [comment]
What is a potential problem with CC-BY? (novice question :P) 
If I understand correctly the first paragraph in the linked law item (såfremt navngivelse er praktisk mulig), at least URL to the cited source and license file should be presented upon citation but if authors are not clear, it is not necessary, right? 
Probably we should make sure that we always make license file and that authors are listed in each repository?

**Comment by arockenberger** [comment]
CC-BY should be just fine, but the original license is cc0 which seems to be problematic in the Norwegian context. The authors should always be clear if one wants to avoid "abandoned works" status which is as good as impossible to reuse, I would feel most comfortable with cc-by

**Comment by naoe-tatara** [comment]
Ah, I see. So the current status is sort of illegal. But in any sense, it is not possible to chase and find any resources that are using materials shown in repositories in this GitHub account and say that they should now show the credit, right? Then is it OK to make CC-BY license as soon as possible?

**Comment by Sabryr** [comment]
Changing the license from CC0 to CC-BY may require contacting every one who has ever made a commits.  We can change it, but need to get emails of everyone contributed and informed them the license will be changed from the date xx-xx. We can not force this on the already forked repos until the next sync.  
(https://creativecommons.org/licenses/by/4.0/legalcode)

**Comment by lexnederbragt** [comment]
I recommend contacting UiO lawyers, asking whether the 'work' we have in these repositories requires CC-BY or can be licensed CC0 - I hope the latter. We are not producing research, papers, lessons, or other work that I see as being 'owned' by someone, so maybe we can still use CC0. juristene@usit.uio.no

**Comment by arockenberger** [comment]
Ok, I think this is more complex than expected. Replying specifically to @Sabryr and @lexnederbragt 

1) We have 2 forks, one by me, one by a former member. Informing them can be handled fairly easily.
2) We have a couple of contributors, see here: https://github.com/uio-carpentry/uio-carpentry.github.io/graphs/contributors, all are active people in our network, and on Github, we can inform them fairly easily, too.
3) We have "mixed content" in our repo: some is software (CC license should NOT be used for software/code), some is images, i.e. our logo, which should have an appropriate license in itself; some is text and for that, according to Norwegian law the person(s) who created it has opphavsrett and CC-BY should be the preferred license.

Proposal: 
* We focus on the "code" part of the repo and put a permissive license (MIT or something). 
* We inform the contributors about this. 
* We put a license OR a description for the use of the logo. 
* We specify that texts are licensed CC-BY but are not the main content of the repo.
* A mere LIST of workshops we've held is not protected by Norwegian opphavsrett anyway.

**Comment by Teebusch** [comment]
Naive question, maybe: Does rewriting the page more or less from scratch solve the issue regarding code content? When I make the Hugo site the only thing that gets carried over is a little bit of intro text on the intro page and the workshop list. I don't think there's any code that's being reused, unless you count markdown as code. 
Code I've added can be licensed under whatever license you guys think fits.

**Comment by arockenberger** [comment]
Looks resolved in https://github.com/uio-carpentry/uio-carpentry.github.io/blob/master/README.md now. Closing the Issue.
