### ISSUE TITLE
Which content under instructor notes?

### ISSUE THREAD

**Issue by Teebusch** [uio-carpentry/uio-carpentry.github.io#18]
Under 'workshops > instructor notes' a bunch of checklists from `organisational/content/workshops/for_instructors` are rendered (onboarding checklist, email template). Should they (all?) be there? 

- I think @naoe-tatara mentioned that the mail templates don't need to be there.
- The checklists don't look very nicely when rendered by the Hugo template (the Github markdown renderer does a better job)

**Comment by naoe-tatara** [comment]
Thanks for this work! 

My understanding is that "Email Examples", "post workshop email template", and "onboarding notes" are all for local coordinators (i.e., atm myself and Annika), and do not have to be open to public or even to instructors, either. 
Regarding the emails: Now it is basically local coordinators who send emails to the participants via registration system (Pindena). The "onboarding notes" is also for those who organize onboarding sessions, which are again local coordinators.

So if possible, I think they can be hidden from the website. If necessary, I would move the contents to the G Suite drive as most likely staff from UB who will be the local coordinator would remain in the board, right?

Regarding the checklists, I think it is OK without looking-nice check-boxes, as they cannot be checked anyways. But if this is too cumbersome, just leave them as they are for now?

(And I am now aware of overlaps between "workshop guide" and "onboarding checklist" and needs for updates in the sense of online format... but I understand that the content updates should be in another issue..)
