### ISSUE TITLE
Show study group member list?

### ISSUE THREAD

**Issue by Teebusch** [uio-carpentry/uio-carpentry.github.io#20]
The old study group website has a member list: https://uio-carpentry.github.io/studyGroup/#contact
I copied the data into `data/members.yml`. It would be possible to parse the yaml and render it on the site, but I wonder if that is necessary / desired?

**Comment by naoe-tatara** [comment]
Hi, as we agreed, can't we have a page of "Carpentry@UiO members" instead of a separate study group members? I started implementing a list of community member based on the consent (@Teebusch , you can find the sheet in the G Suite shared drive). They are taken for both internal (uio.no domain) and this uio-carpentyr.github.io, so please refer the replies to the latter part.

**Comment by Teebusch** [comment]
Similar to #21 : we'll need a meeting with the study group admins.

**Comment by arockenberger** [comment]
Let's do this *kurz und schmerzlos*: we can merge the lists; atm, the StudyGroup is dormant, but I think @annefou and I will revive it when this annoying pandemic is over. It was a great success, especially for community building and socializing!

**Comment by Teebusch** [comment]
Ok, in that case the study group member list from [here](https://github.com/uio-carpentry/uio-carpentry.github.io/blob/master/data/members.yml) should be copied into the UiO Carpentry member list [here](https://github.com/uio-carpentry/uio-carpentry.github.io/blob/master/content/about/members.md) and can then be deleted. 

I count 5 people who are listed as study group members but not carpentry @ UiO members. Do they actually still want to be listed in either of the lists?

**Comment by arockenberger** [comment]
Hard to tell, we had quite a few people moving on. I would not move those members into the active list. If we had an "alumni" list, that would be great. To honour their past contributions.
