### ISSUE TITLE
Unify Code(s) of Conduct

### ISSUE THREAD

**Issue by Teebusch** [uio-carpentry/uio-carpentry.github.io#21]
I've simply copied the code of conduct from the study group site (Mozilla study group code of conduct) and workshops (Carpentries code of conduct) into the same page. I don't think we actually need both. I think we should just remove the study group Code of conduct.

**Comment by Teebusch** [comment]
We'll need a meeting with the study group admins to move forward on this issue.

**Comment by comradekingu** [comment]
Not to mention GitHub has a CoC already. (Edit: Turns out it is called guidelines, but alas)
Why is one layer of redundancy better?

**Comment by Teebusch** [comment]
@comradekingu I'm not sure I understand, Github has a code a conduct already? I think having a code of conduct for Carpentry@UiO activities isn't redundant , and putting it on the website is ok, too. This issue is about merging code of conducts from two separate Carpentry@UiO websites/activities (study group + workshop operations).

**Comment by comradekingu** [comment]
GitHub actually has many, but https://docs.github.com/en/github/site-policy/github-community-guidelines covers the platform itself.
You are talking to me on the same premise as me reading into the plethora of text-files you have put up something I should care about.
One of many problems of foregone conclusions is, as you may find, people don't read these. The people who do, in turn assume of the people that don't to follow them.
The basic premise is that of codifying unwritten rules into navigation of social hierarchy or interaction, and/or hoping antisocial behaviour is somehow less of an issue than disobeying a text-file to the people engaging in it.
If either of those worked, we would be doing it, outside of "don't stick your cat in this microwave notes", which serve a similar American-made purpose. There would in short be no need for a trifecta of power. Some of these things are actually redundant to it. As much as there is no way to pile on text to solve anything, it also doesn't concern its legality. Pretentious.

The effects of the Mozilla code of conduct mindset is, from a former contributor and someone with a lot of friends in Mozilla, an absolute out and out disaster. You would do wisely to stop entering American politics into Norwegian society. It is not in our culture, and it evidently doesn't work at either end.

It escalates conflict beyond the control of individuals, and lends itself to the abuse of people seeking to enter a position of meddling in it without any oversight. It does so by aping the institutions of justice, and banks on legal defence anyway. A CoC is the tool of the mafia, the catholic church, and those seeking to present themselves as a grassroots community.

There is no reasonable assumption to be made about having one, and there is no functional outcome beyond what could be done anyway. No meritocratic authority is to be found in its governance, which is the very point attemptedly made by their creation. It could for case of argument be removed from that into virtue-signalling in corporate fashion. Also out of place.

The actual texts have more specific problems than I care to mention. Do head over to the psychology department to get some insight into why that is.

Here is the central concept of what consequently _doesn't_ make for a Code of Conduct. You are free to use it as "CONTACT.md" or similar, in place of such a convention.

```
Welcome to the UIO Carpentry community

Accept and offer criticism constructively. Let anyone have the privacy they desire.
Settle differences within these boundaries.
Finding yourself unable to do so, e-mail e-post@adresse.no, answered by 1, 2 3, the project maintainer(s).


Velkommen til UIO Carpentry-gemenskapen

Godta og tilby kritikk på konstruktivt vis. Innvilg alle det privatlivet de ønsker.
Løs problemer innenfor disse rammene.
Skulle dette vise seg vanskelig, kan du kontakte e-post@adresse,no besvart av prosjektets vedlikehold(er) 1,2,3.
```

Further, the licensing seems haphazardly put together, and I don't think putting things in the public domain under Norwegian jurisdiction actually works. Much less so with more and other contributors of course.

**Comment by Teebusch** [comment]
Thanks, food for thought!

The license mess is tracked separately, in issue #11. CC0 is indeed not compatible with Norwegian legislation.

**Comment by arockenberger** [comment]
As one of the StudyGroup admins, I think it is OK to substitute the StudyGroup CoC with the Carpentry@UiO CoC, since we are an offspring of it.

Regarding the CC0: #11 is solved now!

Best,

Annika
