### ISSUE TITLE
Add contact info

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/uio-carpentry.github.io#28]
I just realised that thew website does not seem to inform folks on how contact us. I think it would be good to add that information at least to the "who are we" page, but perhaps also on the homepage.

**Comment by Teebusch** [comment]
There's also a "stub" that mentions the mailing lists on the members page (https://uio-carpentry.github.io/about/members/).
Maybe we should provide more complete information about other websites we have, mailing lists (and how to sign up).

**Comment by Teebusch** [comment]
closed by #35
