### ISSUE TITLE
Which courses should show in upcoming course agenda?

### ISSUE THREAD

**Issue by Teebusch** [uio-carpentry/uio-carpentry.github.io#29]
This came up during the redesign meeting:
We need to decide whether only carpentries courses should be shown in the [upcoming workshop list](https://uio-carpentry.github.io/workshops/), or also, e.g., CodeRefinery. 
Depending on what we decide, the automatically created list of upcoming courses from the UiO website might not fit the bill and we might want to add a short pragraph to link to the other organizations' event lists.

**Comment by arockenberger** [comment]
I think since CodeRefinery is such an established and self-contained community, we should not feed in their courses here. Let's limit it to Carpentries and Carpentries-style workshops we have been hosting at UiO, incl. the TidyVerse ones, even though they are independently developed.

**Comment by Teebusch** [comment]
I agree. This matches the status quo. Can this issue be closed then?

**Comment by arockenberger** [comment]
Will close! Thanks for your good work!
