### ISSUE TITLE
Redirect original sources

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/uio-carpentry.github.io#36]
Now that we have a new website, the sources we have incorporated should redirect to it, or at least mention the new website. These are the ones we need to address - please add others if I forgot any

- [x] https://github.com/uio-carpentry/governance

**Comment by Teebusch** [comment]
Like this? https://github.com/uio-carpentry/governance/pull/28 (for the gov docs. The org docs are still maintained in the original repo, they just get imported as modules here. We should add a note about this in the org-repo readme)

**Comment by lexnederbragt** [comment]
I would not maintain these docs in another repo, I fear this is confusing. Why not keep everything here?

**Comment by Teebusch** [comment]
With the org docs, merely importing them here allows to

- keep them together with the org docs that are _not_ rendered on the website (only two documents are rendered here, but there are many more in the org repo)
- keep them separate from non-org stuff -- as intuitive as I think the Hugo file structure is for modifying content, the org docs would be buried a bit in this repo. They are much easier to find if they are in a separate repo.
- separate responsibility between people. The org repo can be maintained and administered by other people than the website.

I've already added a bunch of explanation/comments about this in this repo, so if anyone comes looking for the org files here they should not be confused for long. However, I can certainly add more...

**Comment by lexnederbragt** [comment]
Got it, and I agree. So we remove the content from https://github.com/uio-carpentry/governance but keep documents currently in https://github.com/uio-carpentry/organisational there also in the future. Issue adjusted.

**Comment by Teebusch** [comment]
closing this because the governance repo has been archived.  We might eventually need to open a new issue for the Study group repo, but that is on hold for now.
