### ISSUE TITLE
No upcoming events

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/uio-carpentry.github.io#57]
I thought https://uio-carpentry.github.io/workshops/ under 'Upcoming Workshops' is supposed to show upcoming workshops from https://www.ub.uio.no/english/courses-events/courses/other/Carpentry/. Currently it is not. Any idea what could be the problem?

**Comment by arockenberger** [comment]
There's a problem with the site biilding. @naoe-tatara and I tried to fix it, but it doesn't work. Perhaps @Teebusch could help us?

**Comment by Teebusch** [comment]
On first sight this doesnt seem to be a problem with the event-feed itself but a problem with the GitHub actions deployment config. The last successful build was 2 months ago. The build needs to be successful to keep the event feed up to date (the build automatically runs once a day, iirc). Check the GitHub actions build log for the errors and suggested solutions.

 I'm on vacation, so I cannot do it myself right now. If you cannot fix it, ping me again next week in case I forget.

**Comment by arockenberger** [comment]
Still unresolved; I have no capacity to fix this. Anyone else?

**Comment by Teebusch** [comment]
I suggested to fix it by removing the description from the output. Not optimal, but better than not rendering any events, I suppose. See #58
When merged, perhaps open a new issue "nop description for events" (non-critical) and refer to this one.
Cheers!

**Comment by lexnederbragt** [comment]
Thanks!
